ninety_nine_cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   resources :cats
end

ninety_nine_cats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ninety_nine_cats/app/models/cat.rb
class Cat < ApplicationRecord
  validates :color, inclusion: { in: %w(black white brown yellow red blue orange),
  message: "%{value} is not a valid color" }, presence: true
  validates :sex, inclusion: { in: %w(M F),
  message: "%{value} is not 'M' or 'F' " }, presence: true
  validates :age, :birth_date, :color, :sex, :name, :description, presence: true
end

ninety_nine_cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

ninety_nine_cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def new 
    cat = Cat.new(params.require(:cat).permit(:age, :birth_date, :color, :sex, :name, :description))
    if cat.save
        render json: cat
    else
      render json: cat.errors.full_messages, status: :unprocessable_entity
    end
  end


end

ninety_nine_cats/app/helpers/application_helper.rb
module ApplicationHelper
end

ninety_nine_cats/app/views/cats/index.html.erb
<ul>
  <%@cats.each do |cat|%>
    <li>Name: <%= cat.name %></li>
    <li><a href="<%= cat_url(cat.id) %>">Go to Cat show page</a></li>
  <% end %>
</ul>

ninety_nine_cats/app/views/cats/new.html.erb
<table>
    <thead>
        <tr>
            <th colspan="2">New Cat</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>The table body</td>
            <td>with two columns</td>
        </tr>
    </tbody>
</table>

ninety_nine_cats/app/views/cats/show.html.erb
<ul>
    <li>Birthdate: <%= @cat.birth_date %></li>
    <li>Color: <%= @cat.color %></li>
    <li>Sex: <%= @cat.sex %></li>
    <li>Age: <%= @cat.age %></li>
  </ul>

ninety_nine_cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinetyNineCats</title>
   
  </head>

  <body>
    <%= yield %>
  </body>
</html>